<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126151620 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Enable UUID extension
        $this->addSql('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');

        // Drop admin table if exists
        $this->addSql('DROP TABLE IF EXISTS admin');

        // Add temporary UUID columns
        $this->addSql('ALTER TABLE "user" ADD COLUMN id_uuid UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE notification ADD COLUMN user_id_uuid UUID DEFAULT NULL');

        // Generate UUIDs for existing users
        $this->addSql("UPDATE \"user\" SET id_uuid = uuid_generate_v4()");

        // Update notifications with new UUIDs
        $this->addSql('UPDATE notification SET user_id_uuid = u.id_uuid FROM "user" u WHERE notification.user_id = u.id');

        // Drop old foreign key constraints
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT IF EXISTS fk_notification_user');

        // Drop old columns
        $this->addSql('ALTER TABLE notification DROP COLUMN user_id');
        $this->addSql('ALTER TABLE "user" DROP COLUMN id');

        // Rename UUID columns to original names
        $this->addSql('ALTER TABLE "user" RENAME COLUMN id_uuid TO id');
        $this->addSql('ALTER TABLE notification RENAME COLUMN user_id_uuid TO user_id');

        // Make id NOT NULL and add primary key
        $this->addSql('ALTER TABLE "user" ALTER COLUMN id SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD PRIMARY KEY (id)');

        // Make user_id NOT NULL and add foreign key
        $this->addSql('ALTER TABLE notification ALTER COLUMN user_id SET NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_notification_user ON notification (user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, phone_number VARCHAR(20) NOT NULL, otp_code VARCHAR(6) DEFAULT NULL, otp_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_880e0d766b01bc5b ON admin (phone_number)');
        $this->addSql('ALTER TABLE notification ALTER user_id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
