<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124183307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Change Restaurant ID to UUID and add slug column';
    }

    public function up(Schema $schema): void
    {
        // Drop the old restaurant table and recreate with UUID
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649B1E7706E');
        $this->addSql('DROP INDEX UNIQ_8D93D649B1E7706E');
        $this->addSql('DROP TABLE restaurant');

        // Create new restaurant table with UUID and slug
        $this->addSql('CREATE TABLE restaurant (id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB95123F989D9B62 ON restaurant (slug)');

        // Update user.restaurant_id to UUID and recreate foreign key
        $this->addSql('ALTER TABLE "user" ALTER restaurant_id TYPE UUID USING NULL');
        $this->addSql('UPDATE "user" SET restaurant_id = NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649B1E7706E ON "user" (restaurant_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_EB95123F989D9B62');
        $this->addSql('ALTER TABLE restaurant DROP slug');
        $this->addSql('ALTER TABLE restaurant ALTER id TYPE INT');
        $this->addSql('ALTER TABLE restaurant ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER restaurant_id TYPE INT');
    }
}
